<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import AdminWorkspaceShell from '~/components/dashboard/AdminWorkspaceShell.vue'
import CrudConfirmModal from '~/components/dashboard/CrudConfirmModal.vue'
import { useAdminUpload } from '~/composables/useAdminUpload'

definePageMeta({ layout: 'admin', adminSearchPlaceholder: 'Tìm khóa học, giảng viên...' })
interface AdminCourse { id: number; title: string; description?: string; thumbnail?: string | null; status: string; reject_reason?: string | null; lessons_count?: number; enrollments_count?: number; instructor?: { name: string; avatar?: string | null } | null; category?: { name: string } | null }
interface CategoryItem { id: number; name: string }
interface CourseListResponse { data: AdminCourse[]; current_page: number; last_page: number; total: number }
const user = useAuthUserCookie(); const token = useAuthTokenCookie(); if (!user.value || !token.value) await navigateTo('/login', { replace: true })
const { uploadImage } = useAdminUpload(); const search = ref(''); const status = ref('pending_review'); const loading = ref(false); const courses = ref<AdminCourse[]>([]); const categories = ref<CategoryItem[]>([])
const currentPage = ref(1); const lastPage = ref(1); const totalCourses = ref(0); const errorMessage = ref(''); const successMessage = ref('')
const approveOpen = ref(false); const rejectOpen = ref(false); const createOpen = ref(false); const selectedCourse = ref<AdminCourse | null>(null); const rejectForm = reactive({ reason: '' })
const createForm = reactive({ title: '', description: '', price: 0, category_id: '', thumbnail: '' }); const createSaving = ref(false); const thumbnailFile = ref<File | null>(null); const uploadingThumbnail = ref(false)
const statuses = [{ label: 'Tất cả', value: '' }, { label: 'Chờ duyệt', value: 'pending_review' }, { label: 'Đã xuất bản', value: 'published' }, { label: 'Bản nháp', value: 'draft' }, { label: 'Bị từ chối', value: 'rejected' }]
const authHeaders = () => ({ Authorization: `Bearer ${token.value}` })
const statusLabel = (value: string) => ({ pending_review: 'Chờ duyệt', published: 'Đã xuất bản', rejected: 'Bị từ chối', draft: 'Bản nháp' }[value] || value)
const statusClass = (value: string) => ({ pending_review: 'role-student', published: 'role-instructor', rejected: 'role-admin', draft: 'role-admin' }[value] || 'role-admin')
const pendingCount = computed(() => courses.value.filter(item => item.status === 'pending_review').length)
async function fetchCourses(page = 1) { loading.value = true; try { const query = new URLSearchParams({ page: String(page), per_page: '8' }); if (search.value.trim()) query.set('search', search.value.trim()); if (status.value) query.set('status', status.value); const response = await useApi<CourseListResponse>(`/admin/courses?${query.toString()}`, { headers: authHeaders() }); courses.value = response.data; currentPage.value = response.current_page; lastPage.value = response.last_page; totalCourses.value = response.total } catch (error: any) { errorMessage.value = error?.data?.message || 'Không thể tải danh sách khóa học.' } finally { loading.value = false } }
async function fetchCategories() { categories.value = await useApi<CategoryItem[]>('/admin/categories', { headers: authHeaders() }) }
async function approveCourse() { if (!selectedCourse.value) return; try { await useApi(`/admin/courses/${selectedCourse.value.id}/approve`, { method: 'PUT', headers: authHeaders() }); successMessage.value = `Đã phê duyệt khóa học "${selectedCourse.value.title}".`; approveOpen.value = false; await fetchCourses(currentPage.value) } catch (error: any) { errorMessage.value = error?.data?.message || 'Không thể phê duyệt khóa học.' } }
async function rejectCourse() { if (!selectedCourse.value || !rejectForm.reason.trim()) return; try { await useApi(`/admin/courses/${selectedCourse.value.id}/reject`, { method: 'PUT', headers: authHeaders(), body: { reject_reason: rejectForm.reason } }); successMessage.value = `Đã từ chối khóa học "${selectedCourse.value.title}".`; rejectOpen.value = false; rejectForm.reason = ''; await fetchCourses(currentPage.value) } catch (error: any) { errorMessage.value = error?.data?.message || 'Không thể từ chối khóa học.' } }
async function uploadCourseThumbnail() { if (!thumbnailFile.value) return; uploadingThumbnail.value = true; try { const uploaded = await uploadImage(thumbnailFile.value, 'courses', createForm.thumbnail || null); createForm.thumbnail = uploaded.url } finally { uploadingThumbnail.value = false } }
async function createCourse() { if (!createForm.title.trim()) return; createSaving.value = true; try { await useApi('/courses', { method: 'POST', headers: authHeaders(), body: { title: createForm.title.trim(), description: createForm.description || null, price: Number(createForm.price || 0), category_id: createForm.category_id ? Number(createForm.category_id) : null, thumbnail: createForm.thumbnail || null } }); successMessage.value = 'Đã tạo khóa học mới ở trạng thái bản nháp.'; createOpen.value = false; Object.assign(createForm, { title: '', description: '', price: 0, category_id: '', thumbnail: '' }); thumbnailFile.value = null; await fetchCourses(1) } catch (error: any) { errorMessage.value = error?.data?.message || 'Không thể tạo khóa học.' } finally { createSaving.value = false } }
onMounted(async () => { await Promise.all([fetchCourses(), fetchCategories()]) })
</script>

<template>
  <AdminWorkspaceShell :breadcrumb="['Trang chủ', 'Kiểm duyệt khóa học']" description="Trang kiểm duyệt khóa học tập trung vào việc rà soát nội dung chờ duyệt, hình ảnh đại diện và giảng viên phụ trách trước khi xuất bản; đồng thời cho phép admin tạo khóa học mới." title="Kiểm duyệt khóa học">
    <section class="crud-overview-grid"><article class="dashboard-card mini-card tone-green"><p class="mini-title">Tổng khóa học</p><div class="mini-head"><strong>{{ totalCourses }}</strong><span>Theo bộ lọc hiện tại</span></div></article><article class="dashboard-card mini-card tone-amber"><p class="mini-title">Chờ duyệt</p><div class="mini-head"><strong>{{ pendingCount }}</strong><span>Cần rà soát nội dung</span></div></article><article class="dashboard-card mini-card"><p class="mini-title">Hình ảnh</p><div class="mini-head"><strong>Preview</strong><span>Hiển thị ảnh trực tiếp từ đường dẫn backend</span></div></article></section>
    <section class="dashboard-card crud-panel"><div class="crud-toolbar"><form class="crud-toolbar-main" @submit.prevent="fetchCourses(1)"><input v-model="search" class="crud-search" type="text" placeholder="Tìm theo tên hoặc mô tả khóa học..."><select v-model="status" class="crud-select"><option v-for="item in statuses" :key="item.value" :value="item.value">{{ item.label }}</option></select><button class="crud-secondary-btn" type="submit">Tìm kiếm</button></form><button class="crud-primary-btn" type="button" @click="createOpen = true">Tạo khóa học</button></div><div v-if="errorMessage" class="crud-alert is-error">{{ errorMessage }}</div><div v-if="successMessage" class="crud-alert is-success">{{ successMessage }}</div><div class="crud-table-wrap"><table class="crud-table"><thead><tr><th>Khóa học</th><th>Giảng viên</th><th>Danh mục</th><th>Trạng thái</th><th>Chỉ số</th><th>Thao tác</th></tr></thead><tbody><tr v-if="loading"><td colspan="6" class="crud-empty">Đang tải dữ liệu khóa học...</td></tr><tr v-else-if="courses.length === 0"><td colspan="6" class="crud-empty">Chưa có khóa học phù hợp bộ lọc.</td></tr><tr v-for="course in courses" :key="course.id"><td><div class="crud-course"><div class="crud-course-thumb"><img v-if="course.thumbnail" :src="course.thumbnail" :alt="course.title"><span v-else>📘</span></div><div><strong>{{ course.title }}</strong><RichTextContent :content="course.description" compact empty-text="Chưa có mô tả ngắn." /></div></div></td><td>{{ course.instructor?.name || '--' }}</td><td>{{ course.category?.name || '--' }}</td><td><span class="crud-badge" :class="statusClass(course.status)">{{ statusLabel(course.status) }}</span></td><td>{{ course.lessons_count || 0 }} bài · {{ course.enrollments_count || 0 }} học viên</td><td><div class="crud-actions"><button class="action-btn is-view" type="button" @click="navigateTo('/admin/question-bank')">Ngân hàng câu hỏi</button><button class="action-btn is-edit" type="button" @click="selectedCourse = course; approveOpen = true">Phê duyệt</button><button class="action-btn is-delete" type="button" @click="selectedCourse = course; rejectForm.reason = course.reject_reason || ''; rejectOpen = true">Từ chối</button></div></td></tr></tbody></table></div><div class="crud-pagination"><p>Trang {{ currentPage }} / {{ lastPage }}</p><div class="crud-pagination-actions"><button class="crud-secondary-btn" type="button" :disabled="currentPage <= 1" @click="fetchCourses(currentPage - 1)">Trước</button><button class="crud-secondary-btn" type="button" :disabled="currentPage >= lastPage" @click="fetchCourses(currentPage + 1)">Sau</button></div></div></section>
    <CrudConfirmModal :open="approveOpen" title="Phê duyệt khóa học" :description="`Xác nhận phê duyệt khóa học ${selectedCourse?.title || ''}? Khóa học sẽ được hiển thị cho học viên.`" confirm-text="Phê duyệt" @close="approveOpen = false" @confirm="approveCourse" />
    <Teleport to="body"><div v-if="rejectOpen" class="crud-modal-backdrop" @click.self="rejectOpen = false"><div class="crud-modal"><div class="crud-modal-head"><div><p class="section-kicker">Từ chối khóa học</p><h3>{{ selectedCourse?.title }}</h3><p>Nhập lý do từ chối để giảng viên có thể chỉnh sửa và gửi duyệt lại.</p></div><button class="topbar-ghost" type="button" @click="rejectOpen = false">✕</button></div><div class="crud-form-grid"><div class="crud-field crud-field-full"><span>Lý do từ chối</span><RichTextEditor v-model="rejectForm.reason" placeholder="Ví dụ: Hình ảnh thumbnail chưa đúng chuẩn, nội dung cần bổ sung mô tả rõ hơn." enable-images upload-folder="courses" /></div></div><div class="crud-modal-foot"><button class="crud-secondary-btn" type="button" @click="rejectOpen = false">Đóng</button><button class="crud-primary-btn crud-danger-btn" type="button" @click="rejectCourse">Xác nhận từ chối</button></div></div></div></Teleport>
    <Teleport to="body"><div v-if="createOpen" class="crud-modal-backdrop" @click.self="createOpen = false"><div class="crud-modal crud-modal-wide"><div class="crud-modal-head"><div><p class="section-kicker">Tạo mới</p><h3>Tạo khóa học trong admin</h3></div><button class="topbar-ghost" type="button" @click="createOpen = false">✕</button></div><div class="crud-form-grid"><label class="crud-field"><span>Tên khóa học</span><input v-model="createForm.title" type="text" placeholder="Ví dụ: Laravel cho người mới bắt đầu"></label><label class="crud-field"><span>Giá</span><input v-model="createForm.price" type="number" min="0"></label><label class="crud-field"><span>Danh mục</span><select v-model="createForm.category_id"><option value="">Chọn danh mục</option><option v-for="item in categories" :key="item.id" :value="String(item.id)">{{ item.name }}</option></select></label><div class="crud-field crud-field-full"><span>Mô tả khóa học</span><RichTextEditor v-model="createForm.description" placeholder="Mô tả chi tiết khóa học" enable-images upload-folder="courses" /></div><div class="crud-field crud-field-full"><span>Ảnh khóa học</span><div class="crud-image-preview"><img v-if="createForm.thumbnail" :src="createForm.thumbnail" alt="Course thumbnail"><div v-else class="crud-image-fallback">CR</div><div><input type="file" accept="image/*" @change="thumbnailFile = ($event.target as HTMLInputElement)?.files?.[0] || null"><div class="crud-inline-actions crud-modal-foot"><button class="crud-secondary-btn" type="button" :disabled="uploadingThumbnail || !thumbnailFile" @click="uploadCourseThumbnail">{{ uploadingThumbnail ? 'Đang tải...' : 'Tải ảnh lên' }}</button></div></div></div></div></div><div class="crud-modal-foot"><button class="crud-secondary-btn" type="button" @click="createOpen = false">Đóng</button><button class="crud-primary-btn" type="button" :disabled="createSaving" @click="createCourse">{{ createSaving ? 'Đang tạo...' : 'Tạo khóa học' }}</button></div></div></div></Teleport>
  </AdminWorkspaceShell>
</template>
